name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: rootroot
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432    
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5 
    steps:
    - uses: actions/checkout@v2

    - name: Install golang-migrate
      run:  |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo  mv migrate.linux-amd64 /user/bin/migrate
        which migrate

    - name: Run migrations
      run: make migrateup

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    # - name: Build
    #   run: go build -v ./...

    - name: Test
      run: make test
